name: e2e testing

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run on chrome
        uses: cypress-io/github-action@v3
        with:
          command: cypress run --browser chrome --component
      - name: Cypress run on firefox
        uses: cypress-io/github-action@v3
        with:
          command: cypress run --browser firefox --component
      - name: Cypress run on electron
        uses: cypress-io/github-action@v3
        with:
          command: cypress run --browser electron --component